"""Pure-torch GRPO loss math (no toolkit/tamm dependency, so it's unit-testable
without loading the 3B). Imported by train_adapter_grpo.py.

GRPO (Shao et al., 2024) without a value network: for a GROUP of G on-policy
drafts sampled for the SAME task, each draft i gets a scalar reward r_i from the
frozen Sonnet rubric judge. The group's own mean is the baseline (no critic), so
the advantage is the group-relative, std-normalised reward:

    A_i = (r_i - mean_group) / (std_group + eps)

and the policy is pushed up on positive-advantage drafts, down on negative ones:

    L_pg = - mean_i ( A_i * seq_mean_logprob(draft_i) )

We reuse `seq_mean_logprob` from orpo_loss.py for the per-sequence log-prob, so
the only new math here is the advantage and the policy-gradient term. Because we
do ONE gradient pass over each rollout batch (the rollouts are regenerated by the
real on-device model each outer iteration), the importance ratio is ~1 and the
PPO clip degenerates — so v1 drops it. An OPTIONAL KL-to-reference term is
supported via PRE-COMPUTED reference log-probs (the SFT-init adapter scored on the
same fixed drafts), keeping the policy near the 0.409 init without a second model
in the training loop.
"""
import torch
import torch.nn.functional as F


def group_advantages(rewards, group_ids, eps=1e-4, normalize_std=True):
    """Group-relative advantages. `rewards` [N], `group_ids` [N] (same int id for
    drafts of the same task). Returns A [N], detached-safe (pure function of inputs).

    A_i = (r_i - mean_group) - optionally / (std_group + eps). A group whose drafts
    all scored equally (std 0) contributes zero advantage to every member — it gives
    no preference signal, which is correct (nothing to learn from a flat group).
    """
    rewards = rewards.float()
    adv = torch.zeros_like(rewards)
    for g in torch.unique(group_ids):
        m = group_ids == g
        r = rewards[m]
        centered = r - r.mean()
        if normalize_std:
            centered = centered / (r.std(unbiased=False) + eps)
        adv[m] = centered
    return adv


def grpo_policy_loss(seq_logprobs, advantages, ref_logprobs=None, beta_kl=0.0):
    """GRPO policy-gradient loss from per-sequence mean log-probs and advantages.

    seq_logprobs : [B] current-policy mean token log-prob over each draft's response
                   (from seq_mean_logprob); REQUIRES grad.
    advantages   : [B] group-relative advantages; treated as constants (detached).
    ref_logprobs : [B] OPTIONAL frozen reference (SFT-init) mean log-probs over the
                   SAME drafts; constants. If given with beta_kl>0, adds a sequence-
                   level KL-ish anchor beta_kl * mean( (lp - ref)^2 ) that penalises
                   drift from the init in BOTH directions (a cheap, ref-model-free
                   regulariser; not the exact k3 token KL, but stable for a short run).
    Returns a scalar loss.
    """
    adv = advantages.detach().to(seq_logprobs.dtype)
    pg = -(adv * seq_logprobs).mean()
    if ref_logprobs is not None and beta_kl > 0.0:
        anchor = beta_kl * ((seq_logprobs - ref_logprobs.detach().to(seq_logprobs.dtype)) ** 2).mean()
        return pg + anchor
    return pg
